let modelArray = [
    {
        id:1,
        category:"Electric",
        type:"Crossover",
        title:"C40 Recharge",
        desc:`세제혜택 후 판매가격 (*보조금 미포함)<br>KRW 68,650,000`,
        img:["c40-electric.avif"],
    },
    {
        id:2,
        category:"Electric",
        type:"SUV",
        title:"XC40 Recharge",
        desc:`세제혜택 후 판매가격 (*보조금 미포함) <br>KRW 67,690,000`,
        img:["xc40-electric.avif"],
    },
    {
        id:3,
        category:"Electric",
        type:"SUV",
        title:"EX30",
        desc:`소비자 판매가격 <br>KRW 49,450,000`,
        img:["ex30-reveal.avif"],
    },
    {
        id:4,
        category:"Plug-in hybrids",
        type:"SUV",
        title:"XC90 Recharge",
        desc:`소비자 판매가격 <br>KRW 115,200,000`,
        img:["xc90-hybrid.avif"],
    },
    {
        id:5,
        category:"Plug-in hybrids",
        type:"SUV",
        title:"XC60 Recharge",
        desc:`소비자 판매가격<br> KRW 86,400,000`,
        img:["xc60-hybrid.avif"],
    },
    {
        id:6,
        category:"Plug-in hybrids",
        type:"Sedan",
        title:"S90 Recharge",
        desc:`소비자 판매가격<br> KRW 87,900,000`,
        img:["s90-hybrid.avif"],
    },
    {
        id:7,
        category:"Mild hybrids",
        type:"SUV",
        title:"XC90",
        desc:`소비자 판매가격 <br>KRW 87,200,000`,
        img:["xc90.avif"],
    },
    {
        id:8,
        category:"Mild hybrids",
        type:"SUV",
        title:"XC60",
        desc:`소비자 판매가격 <br>KRW 63,400,000`,
        img:["xc60.webp"],
    },
    {
        id:9,
        category:"Mild hybrids",
        type:"SUV",
        title:"XC40",
        desc:`소비자 판매가격 <br>KRW 49,200,000`,
        img:["xc40.avif"],
    },
    {
        id:10,
        category:"Mild hybrids",
        type:"Sedan",
        title:"S90",
        desc:`소비자 판매가격 <br>KRW 64,000,000`,
        img:["s90.avif"],
    },
    {
        id:11,
        category:"Mild hybrids",
        type:"Sedan",
        title:"S60",
        desc:`소비자 판매가격 <br>KRW 56,400,000`,
        img:["s60.avif"],
    },
    {
        id:12,
        category:"Mild hybrids",
        type:"CROSS COUNTRY",
        title:"V90 Cross Country",
        desc:`소비자 판매가격 <br>KRW 72,500,000`,
        img:["v90-cross-country.avif"],
    },
    {
        id:12,
        category:"Mild hybrids",
        type:"CROSS COUNTRY",
        title:"V60 Cross Country",
        desc:`소비자 판매가격 <br>KRW 56,300,000`,
        img:["v60-cross-country.avif"],
    },



]